spring.application.name=galeria-estoque-api

# 1. Conexão com o Banco
spring.datasource.url=jdbc:postgresql://localhost:5432/db_gestao_estoque
spring.datasource.username=postgres
spring.datasource.password=1234

# 2. Hibernate e Logs
# atualizar automaticamente o banco de dados.
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Java está enviando
spring.jpa.show-sql=true

#Quebra e organiza as linhas do código SQL
spring.jpa.properties.hibernate.format_sql=true

# 3. Porta e Documentação

server.port=8080
#Cria uma página automática de testes (chamada Swagger).
springdoc.swagger-ui.path=/swagger-ui.html
